version: "2"
sql:
  - engine: "mysql"
    queries: "../../internal/mysql/queries/*.sql"
    schema: "../../internal/mysql/migrations/*.sql"
    gen:
      go:
        package: "generated"
        out: "../../internal/mysql/generated"
        emit_json_tags: true
        emit_interface: true
        overrides:
          - db_type: "int"
            go_type: "uint32"
          - column: "products.regular_price"
            go_type: "float64"
          - column: "products.discounted_price"
            go_type: "float64"
          - column: "orders.amount"
            go_type: "float64"
          - column: "orders.shipping_amount"
            go_type: "float64"
          - column: "order_items.price"
            go_type: "float64"
