basePath: /api/v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:3030
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for the ecommerce website.
  license:
    name: Mozilla Public License Version 2.0
    url: https://www.mozilla.org/en-US/MPL/2.0/
  title: Crocheted Ecommerce API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerToken:
    type: basic
swagger: "2.0"
